apiVersion: v1
kind: Template
metadata:
  name: centos-template 
  annotations:
    description: "Description" 
    iconClass: "icon-python" 
    tags: "base,centos" 
objects:   
- apiVersion: v1
  kind: Pod
  metadata:
    name: base-centos
  spec:
    containers:
    - command:
      - /bin/sh
      - -c
      - while true; do echo hello world; sleep 60; done
    - env:
      - name: SLEEP_TIME
        value: ${SLEEP_TIME} 
      image: centos:latest
      name: master
      ports:
      - containerPort: 6379
        protocol: TCP
parameters:  
- description: container release
  name: CONTAINER_RELEASE
  value: latest
- description: sleep time
  name: SLEEP_TIME
  value: '60'
labels:      
  centos: base