apiVersion: v1
kind: Template
metadata:
  name: centos-base-container
  annotations:
    description: run a container Ever with a while loop of 60s 
    iconClass: icon-python
    tags: "SIX,Base"
objects:   
- apiVersion: v1
  kind: Pod
  metadata:
    name: centos-base-container
  spec:
    containers:
    - command:
      - /bin/sh
      - -c
      - while true; do echo hello world; sleep ${SLEEP_TIME}; done
    - env:
      - name: SLEEP_TIME
        value: ${SLEEP_TIME} 
      image: centos:${CONTAINER_RELEASE}
      name: ${CONTAINER_NAME}
      ports:
      - containerPort: 8080
        protocol: TCP
parameters:  
- description: describe your container
  name: CONTAINER_NAME
  value: mycontainer
- description: container release
  name: CONTAINER_RELEASE
  value: latest
- description: sleep time
  name: SLEEP_TIME
  value: 60
labels:      
  centos: container



apiVersion: v1
kind: Template
metadata:
  name: centos-template 
  annotations:
    description: "Description" 
    iconClass: "icon-python" 
    tags: "six,baseimage" 
objects:   
- apiVersion: v1
  kind: Pod
  metadata:
    name: ${CONTAINER_NAME}
  spec:
    containers:
    - command:
      - /bin/sh
      - -c
      - while true; do echo hello world; sleep ${SLEEP_TIME}; done
    - env:
      - name: SLEEP_TIME
        value: ${SLEEP_TIME} 
      image: centos:${CONTAINER_RELEASE}
      name: ${CONTAINER_NAME}
      ports:
      - containerPort: 8080
        protocol: TCP
parameters:  
- description: describe your container
  name: CONTAINER_NAME
  value: mycontainer
- description: container release
  name: CONTAINER_RELEASE
  value: latest
- description: sleep time
  name: SLEEP_TIME
  value: 60
labels:      
  centos: base

